version: "3"

services:
  api:
    build: .
    command: bash -c "go get github.com/codegangsta/gin && gin -p ${DEV_DOCKER_PORT} run main.go"
    volumes:
      - .:/go/src/pressly-goose-test
    ports:
      - "${DEV_HOST_PORT}:${DEV_DOCKER_PORT}"