version: "3"

services:
  api:
    build: .
    command: bash -c "go get github.com/codegangsta/gin && gin -p 3000 run main.go"
    volumes:
      - .:/go/src/pressly-goose-test
    ports:
      - "3000:3000"